channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numba
  - pyyaml>=5.3.1
  - pandas>=1.2.3
  - scipy>=1.6.2
  - numpy>=1.20.2
  - leidenalg>=0.8.3
  - louvain>=0.7.0
  - plotnine>=0.8.0
  - harmonypy>=0.0.5
  - scrublet>=0.2.3
  - bbknn>=1.4.1
  - kneed>=0.7.0
  - keras-gpu>=2.4.3
  - tensorflow-gpu>=2.4.1
  - scikit-learn>=0.24
  - joblib>=1.0.1
  - scanpy
  - pip
  - pip:
    - cellex>=1.2.1
    - git+https://github.com/wtsi-hgi/sccaf.git