name: conda_cellbender
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numba<0.53.0
  - scikit-learn>=0.24
  - pytables
  - torchvision
  - pandas
  - numpy
  - scipy
  - python-igraph
  - plotnine
  - kneed
  - louvain
  - leidenalg
  - click
  - plotnine
  - matplotlib
  - pip
  - pip:
     - git+https://github.com/theislab/scanpy.git@1.7.0rc1